# Introduction
With the advent of large and remote data sources comes a need properly understand the methods for interacting with such data. 
The Cal Poly statistics department, at the current time, lacks a formal remote data course. This leaves it up to the discretion 
of professors to include such material in their courses, and possibly leaves students to learn these essential skills outside of the classroom.

The technical purpose of this book is to demonstrate how to *connect to*, *upload data to*, and *read data from* the statistics department online dataset repository.
The skills presented in this book can be easily adapted to any other remote source that students may come across in their courses or in the field. 

# What's a Database, Anyway?
As a statistics student at Cal Poly, you most likely have heard of databases, but rarely are you presented with a plain english explanation of what they are.
A database, for our purposes, acts as a single location where all of our datasets are stored, waiting for analysis. Imagine having a folder on your computer 
where you could only save csv files and you have to specify the contents of those files before you save them. Additionally, imagine that this folder exits in something like a Google Drive,
so if you have the right password, you can access the data from anywhere. A database acts like this in some regards, along
with extra security so that no one can just open the folder and mess with your data. 

Formally, all the statistics department datasets are stored in a *relational database*, meaning that they are stored in a standardized, tabular format. The tables are related according to 
specific columns, or *keys*. Additionally, they are stored in a remote server that can be accessed from any computer with an internet connection and the proper 
usernames and passwords.

# Questions concerning Queries 
When we talk about databases, we usually talk about sending "queries" to them. Sending a query is a way of asking the database give us certain data tables. Typically,
we send a request to the database, where the database software figures out what data we want based on the query, and gives it to us if possible. Since we can be denied 
data if we ask for it incorrectly or if we don't have the proper passwords, we aren't really "fetching" data. It's a bit more like "asking" for data and being given it 
if appropriate. In this regard, the name "query" makes a little more sense.

# Sequels and Prequels 
A relational database actually has it's own language for queries, called SQL (and pronounced Sequel). There's a number of classes on campus that teach the
syntax and advanced uses of the sql language, such as the Statistic's department's STAT 441. If you haven't already seen SQL I would highly suggest taking stat 441
or the computer science database course to get into some of the really cool features of SQL. If you don't have the time or the prerequisite necessary for those, 
there's a ton of  Luckily for us, SQL is very statistical in nature and many of the languages you've already encountered can easily translate to sql. The below code is
a simple "Rosetta Stone" that you can use to translate code from R or SAS into SQL. Given the iris dataset, all the following code blocks will output the same data. 

**R - Tidyverse**
```{r}
 iris_subset = iris %>% 
                group_by(Species) %>% 
                arrange(Petal.Width) %>%
                filter(Petal.Length > 2) %>%
                select(Sepal.Length, Sepal.Width)
```

**SAS - Data Step**
```{sas}
proc sort data = iris;
by species, petal width;
run; 

data iris_subset;
set iris;
if Petal.Length > 2;
keep Sepal.Length Sepal.Width;
run;

```
**SQL**
```{sas}

SELECT Sepal.Length, Sepal.Width 
FROM iris
WHERE Petal.Length > 2
ORDER BY Petal.Width
GROUP BY Species
;

```

If you'd like more practice with SQL consider trying the sqldf R package to use SQL language to manipulate DataFrames. If you prefer SAS, try swapping your data step 
with Proc Sql. 