# Web API
Application programming interfaces, or API’s, loosely refer to inputs a user can submit to a computer program.  If that sounds vague, don’t worry. The term API can cover a broad range of situations and in this section of the tutorial we are going to cover some of the basics of a more specific Web API. 

For statistical purposes, a web API is a method of integrating downloading data from a website into your code.Unlike SQL queries, web API requests are specific to the website you are attempting to download from to allow more flexibility. Web API’s are used by a variety of developers to request and retrieve data, and the tabular structure of returned by a SQL query may not be ideal. Web API’s utilize specific URL strings to locate the data that you wish to request, and typically give it to you in a format known as JSON. To address the first requirement, it’s ideal to do a quick web search and find the documentation of the API so that you understand the URL syntax. Assuming you have that correct and the website grants your request for data, the last step is to convert the JSON data to something a bit more usable for statistics. 

In this section, we'll be using the COVID tracking API. More information on this API can be found [here](https://covidtracking.com/api).

## Julia

**imports**
```julia
using HTTP, JSON, DataFrames, Query
```

**Enter the Correct URL and make the request**
```julia
urlcacurrent = "https://covidtracking.com/api/v1/states/CA/current.json"
rawdata=HTTP.get(urlcurrent)
```
**Parse the JSON data**
```julia
#select the body of the API call, convert it into a string
JSONdata = rawdata.body |> String

#parse JSON data, convert it into a DataFrame

CACOVID = JSONdata |> JSON.parse |> DataFrame

```

## R

To connect to APIs in R, we utilize the `httr` and `jsonlite` packages.

```r
library(httr)
library(jsonlite)
```

To get data from an API, we'll use the `GET` command from the `httr` library. This function takes in a URL and can also take in extra parameters, depending on the API.

```r
res <- GET("https://covidtracking.com/api/v1/states/current.json")
res
```
```
Response [https://covidtracking.com/api/v1/states/current.json]
  Date: 2020-05-20 03:17
  Status: 200
  Content-Type: application/json
  Size: 45 kB
```

Looking into the res variable, we see a description of our request and what was returned. To look at the data received, we convert the unicode content of the response into characters. APIs typically return data in JSON format, so we can use the `fromJSON` function from the `jsonlite` package to translate this into a dataframe.

```r
json_data <- res$content %>% 
  rawToChar() 
  
data <- json_data %>% 
  fromJSON()
  
head(data)
```
```
state positive positiveScore
1     AK       399            ...
2     AL       12376          ...
...
```

As an example of using an API with other query parameters that you can pass in, lets look at the API for jeopardy trivia questions! Information on this API can be found [here](https://jservice.io/). 

The "random question" section of the API allows you to to pass in a "count" parameter for how many questions you would like. The `GET` function in R can take these query specifications through the `query` parameter as a named list. 

```r
res <- GET(
  "http://jservice.io/api/random",
  query = list(
    count = 2
    # could insert other query specifications here!
  )
)

questions <- res$content %>% 
  rawToChar() %>% 
  fromJSON()
  
questions
```

```
     id       answer                                         question value
1 71610 a centennial   A celebration to mark at 10-decade anniversary  1000  ...
2 71611    Patagonia   ...
...
``` 

## Python

To connect with APIs in Python, we use the `requests` package. We'll also use the `pandas` package later to convert the data into a DataFrame.

```
import requests
import pandas as pd
```

To get data from an API, we'll use the `get` command from the `requests` library. This function takes in a URL and can also take in extra parameters, depending on the API. 

```r
req = requests.get("https://covidtracking.com/api/v1/states/current.json")
req
```
```
<Response [200]>
```

Looking into the res variable, we see that our request was successful (status 200). To look at the data received, can use the `json` method of the request. We can convert this into a dataframe with the `DataFrame` function from `pandas`.

```r
json_data = req.json()
data = pd.DataFrame(json_data)
data.head()
```
```
  state  ...                                      hash
0    AK  ...  22375f1c5b622e4c0aee670cc25b05584c1e3341
1    AL  ...  dc3754f5631d38c30317c938b33a1cbcb5a19bee
```

Same as in the `R` section, we'll use the API for jeopardy trivia questions to give an example of how to pass a query parameter to the API.

The "random question" section of the API allows you to to pass in a "count" parameter for how many questions you would like. The `requests.get` function in Python can take these query specifications through the `params` parameter as a dictionary of strings.

```r
req = requests.get("http://jservice.io/api/random", params = {"count": "2"})
json_data = req.json()
data = pd.DataFrame(json_data)
data
```

```
   id  ...                                   category
0  59388  ...  {'id': 2741, 'title': 'think pink'...
1  59389  ...  {'id': 7597, 'title': 'veggie-pourri'...
```

You'll note that because there was an internal obje


## SAS 

**define a temporary file to read the JSON data into**
filename raw_json temp;

use proc http to make the API call

```sas
proc http
url = "https://covidtracking.com/api/v1/us/current.json"
method = "GET"
out = raw_json

QUERY=("parm1" = "val1" "parm2" = "val2");

quit;
```

This api uses the path segement of the url to specify parameters, but ifyou are using an an api that utilizes a query string use
the query option as listed below, or append it directly to the url. If doing the latter, check the api documentation to see what delimiter is used between parameters. Parameters are typically specified in `"parm" = "val"` form.

use the libname statement to convert the json file to a sas table

```sas
libname Calif JSON fileref = raw_json;

proc print data = Calif.alldata;
run;
```
